@startuml web4
|Client|
start
:Choisir produit dans catalogue;
:Acheminer commande et no carte de crédit;

|Fournisseur|
:Commande]
:Analyser commandes;
if (livraison désiré aujourdhui?) then (yes)
:Expédier commandes;
:Bon de facturation]
else (no)

endif
|Client|
:produit;
if (produit défectueux) then (yes)
:Aviser fournisseur produit défectueux;
:retourner produit;
|Fournisseur|
:Produit]
else (no)
:Confirmer paiement par le site web;
@enduml