@startuml
skinparam Style strictuml

title Etats - Types de paiements
state EtatEcran{
Eteint --> Allume: appuyerBoutonDroite()
Allume --> Eteint: appuyerBoutonDroite()

}
[*] --> Eteint
EtatEcran --> EnCharge: brancher()
EnCharge --> Eteint : débrancher()



@enduml