@startuml
skinparam Style strictuml
actor Commis #green
title rdcu reserverChambre avec sejour
note left of ControleurNoterReservation: Controleur de session
 -> ControleurNoterReservation: reserverChambre(\ndateDepart:integer,\n dateArrive:integer,\n nomCategorie:string, \nquantiteChambre: integer)
note right of ControleurNoterReservation: expert\nctrl->dateArrive, datedepart\nr->createur de s:Sejour
ControleurNoterReservation --> "r:Reservation"  : creerSejour(dateArrive:integer, dateDepart:integer)
note right of "r:Reservation": expert\nctrl->categorie,\n categorie -> map<chambres>
"r:Reservation" --> "c:Categorie" : list<Chambre> lc = getChambres(nomCategorie: string, quantiteChambre: integer)
note right of "c:Categorie": expert\ncategorie contient list chambre
"c:Categorie" -> "map<categorie,list<Chambres>>": get(nomCategorie)
note right of "r:Reservation": expert\n r -> ls, \n r->lc
"r:Reservation" -> "ls:List<Sejour>" : add(lc)
note right of "r:Reservation"  : createur\n r contient s:Sejour
"r:Reservation" -->  "s:Sejour" **: ceate(dateArrive:integer, dateDepart:integer, r:Reservation, lc:list<Chambre>)
note right of "r:Reservation" : expert\n r-> s\nr->ls
"r:Reservation" --> "ls:List<Sejour>": add(s)

@enduml
