@startuml
skinparam Style strictuml
participant ControleurNoterReservation as ctrl
participant "cl:Client" as cl
participant "r:Reservation" as r

title rdcu creerNouvelleReservation

note left of ctrl: Controleur de session
 --> ctrl : confirmerReservation(nom:string, telephone:string)

note left of cl: Createur(PUCE) \npar default
ctrl --> cl **: create(nom:string, telephone:string)

note left of r: Expert\nctrl visibilité sur r:Reservation\nCtrl visibilité sur c:Client\nr enregistre le client
ctrl --> r: setClient(c)

note left of r: Expert\nctrl visibilité sur r:Réservation\nr mutateur d'attribut\nnoConfirmation = valeur inique
ctrl->r: generateNumeroConfirmation()

@enduml
