@startuml Notez une réservation
skinparam Style strictuml
class "Emplacement" as e
class "Commis" as CO
class "Client" as CL {
    nom: String 
    telephone: String 
}
class "Reservation" as RE {
    noConfirmation: String 
}
class "Hotel" as HO 
class "Chambre" as CH 
note right: Multiplicité entre Séjour et Chambre\n correspond à la quantité de chambres\n demandé par le client

class "Categorie" as CA {
    nom: String
}

class "Sejour" as SE {
    dateArrive: DateTime 
    dateDépart: DateTime 
}


CO "1" -- "*" RE : effectue >
CL "1" -- "*" RE : demande >
RE "1" -- "*" SE : est pour >
SE "1" -- "*" CH : contient >
HO "1" -- "*" CO : emploie >
HO "1" -- "*" CH : possède >
CH "*" -- "1" CA : appartiennent a >
CH "*" -- "1" e : sont localisé à >
CH "1" -- "*" Cle: est ouverte avec >
 
@enduml
