@startuml terminerReservation
skinparam Style strictuml
title rdcu terminerReservation
participant "ctrl:ControleurNoterReservation" as ctrl 
participant "r:Reservation" as r

note left of ctrl: Controleur de session
-> ctrl: terminerReservation()

note left of r: Expert\nctrl a une visibilité sur r\nr contient plusieurs LigneReservation
ctrl->r: list<:ligneReservation> llr = getLigneReservations()

@enduml
