@startuml Notez une réservation
skinparam Style strictuml
class "Commis" as CO
class "Client" as CL {
    nom: String 
}
class "Reservation" as RE {
    dateArrive: DateTime 
    dateDepart: DateTime
}
class "Hotel" as HO 
class "Chambre" as CH 
class "Categorie" as CA {
    nom: String
}
CO "1" -- "*" RE : effectue >
CL "1" -- "*" RE : demande >
RE "1" -- "1" CH : est pour >
HO "1" -- "*" CO : emploie >
HO "1" -- "*" CH : possède >
CH "*" -- "1" CA : appartiennent a >
 
@enduml
