@startuml reserverChambre
skinparam Style strictuml
title rdcu reserverChambre
participant "ctrl:ControleurNoterReservation" as ctrl
participant "r:Reservation" as r
participant "lr:LigneReservation" as lr
participant "Categorie" as cat 
participant "llr:List<:LigneReservation>"  as llr


note left of ctrl: Controleur de session
-> ctrl: reserverChambre(\ndateDepart:integer,\n dateArrive:integer,\n nomCategorie:string, \nquantiteChambre: integer)

note left of cat: ctrl a une visibilité sur Categorie\nCategorie contient les instances categorie
ctrl->cat: list<:Chambre> lc = getChambresDisponible(nomCategorie,dateDebut,dateFin, quantiteChambre)

note left of r: Expert\nctrl a une visibilité sur r\nr est le createur de lr
ctrl->r: creerLigneReservation(dateArrive,dateDepart,lc)

note left of lr: Createur(PUCE)\nr:Reservation contient lr:LigneReservation
r --> lr **: create(dateArrive,dateDepart,lc)

note left of llr: Expert\nr contient llr\nr possède lr
r->llr: add(lr)
@enduml
