@startuml demarrerTransfertChambre
skinparam Style strictuml
title rdcu demarrerTransfertChambre

participant "ctrl:ControleurTransfertChambre" as ctrl

note left of ctrl: Controleur de session
-> ctrl: demarrerTransfertChambre()

@enduml
