@startuml rechercheChambreComparables
skinparam Style strictuml
title rdcu rechercheChambreComparables
@startuml demarrerTransfertChambre
skinparam Style strictuml
title rdcu demarrerTransfertChambre

participant "ctrl:ControleurTransfertChambre" as ctrl
participant "h:Hotel" as h 
participant "mc:Map<noChambre,:Chambre>" as mc 
participant "chambreActuel:Chambre" as ca 
participant "cat:Categorie" as cat

note left of ctrl: Controleur de session
-> ctrl: rechercherChambreComparables(noChambreActuel:string)

note left of h: Expert\nctrl a une visibilité sur l'objet racine h:Hotel\nh possède une liste de Chambre
ctrl->h: chambreActuel = getChambre(noChambreActuel)

note left of mc: Expert\nh possède plusieurs chambres
h->mc: chambreActuel = get(noChambreActuel)

note left of ca: Expert\nControleur connait chambreActuel\nSejour contient des Chambres
ctrl->ca: sejour = getSejourCourant()

note left of ca: Expert\nContoleur connait chambreActuel\nchambre appartient à une categorie
ctrl->ca: cat = getCategorie()

note left of ctrl: Expert\nctrl connait categorie\nPlusieurs chambres appartiennent à une categorie.
ctrl->cat: List<:Chambre> lcd = getChambreDisponible(now(),sejour.dateFin)


@enduml


@enduml
