@startuml creerNouvelleReservation
skinparam Style strictuml
title rdcu creerNouvelleReservation

participant "ctrl:ControleurNoterReservation" as ctrl
participant "r:Reservation" as r
participant "c:Commis" as c 
participant "Categorie" as cat 
participant "llr:List<:LigneReservation>"  as llr

note left of ctrl: Controleur de session
-> ctrl: creerNouvelleReservation()

note left of r: Createur(PUCE) par default\nforte cohésion+faible couplage pour le paramêtre c:Commis
ctrl --> r **: create(c)

note left of llr: Createur\nr possède plusieur LigneReservation
r --> llr **: create()

note left of cat: Expert\nctrl a une visibilité sur Categorie\nCategorie contient toutes les instances de categorie
ctrl->cat: list<:categorie> lc = getCategories()


@enduml
