@startuml
skinparam Style strictuml
actor Commis
title Transfert de chambre

Commis -> Systeme: demarrerTransfertChambre()
Systeme --> Commis : Demande no chambre

Commis -> Systeme: rechercheChambreComparables(noChambreActuel:string)  
Systeme --> Commis: sejour et chambres disponibles

Commis -> Systeme: transfererChambre(noChambreActuel:string, noNouvelleChambre:string)
Systeme --> Commis: emplacement
@enduml 