@startuml
skinparam Style strictuml
class "MiseEnPlateau" as mp <C01> {
    dateArrive: DateTime
    montant: float

}
class "Magasin" as m <C05,C06>
class "Caissier" as caissier <C05> {
    identifiant: string
    motPasse:string
}
class "Caisse" as caisse {
    estLibre: boolean
}

class "TirroirCaisse" as tc 
class "Plateau" as p {
    identifiant: string
}

caisse "1" -- "1" tc : contient >
mp "1" -- "1" caissier: Fait par >
mp "1" -- "1" p: utilise >
mp "1" -- "1" tc: mets le plateau dans
m "1" -- "*" caissier: emploie >
m "1" -- "*" caisse: possède >
m "1" -- "*" p: possède >



@enduml