@startuml rdcu-...
skinparam Style strictuml

participant ":Caisse" as ctrl
participant "m:Magasin" as m
participant "caissier:Caissier" as caisse
participant "tc:TirroitCaisse" as tc
participant "p:Plateau" as p 
participant "mp:MiseEnPlateau" as mp
participant "mc:Map<identifiant,:Caissier>" as mc

note left of ctrl: Controleur de facade équipement
->ctrl: demarrerMiseEnPlateau()

note left of mp: Createur(PUCE)\nLa miseEnPlateau est fait sur la caisse
ctrl -> mp ** : mp = create()


-> ctrl: authentifierPourMiseEnPlateau(identifiant: string, mdp:string)
ctrl -> m: authentifierPourMiseEnPlateau(identifiant: string, mdp:string)

m -> mc: caissier = get(identifiant



@enduml

