@startuml
skinparam Style strictuml
title rdcu creerNouvelleReservation

@startuml terminerReservation
skinparam Style strictuml
title rdcu terminerReservation
participant "ctrl:ControleurNoterReservation" as ctrl 
participant "r:Reservation" as r
participant "cl:Client" as cl

note left of ctrl: Controleur de session
-> ctrl: confirmerReservation(nomclient:string, telephone: string)

note left of cl: Create(PUCE)\npar default
ctrl -> cl **: create(nomClient,telephone)

note left of r: Expert\nctrl->r\nctrl->c\nCohesion r est une transaction
ctrl->r: setClient(c)

note left of r: Expert\n ctrl a une visibilité sur r\nr mutateur d'attribut noConfirmation\nCohesion 
ctrl -> r: noConfirmation = setNotConfirmationUnique()

@enduml

@enduml
