@startuml
skinparam Style strictuml
title rdcu reserverChambre

participant "ctrl:ControleurNoterReservation" as ctrl 
participant "c:Commis" as c
participant "r:Reservation" as r
participant "llr:list<:ligneReservation" as llr
participant "lr:LigneReservation" as lr
participant "Categorie" as cat
participant "mc:map<nom,:Categorie>" as mc 
participant "categorie:Categorie" as ic

note left of ctrl: Controleur de session
-> ctrl: reserverChambre(\ndateDepart:integer,\n dateArrive:integer,\n nomCategorie:string, \nquantiteChambre: integer)

note left of cat: Expert\nctrl a une visibilité sur Categorie\nCategorie contient map<:Categorie>
ctrl->cat: list<:Chambre> chambres = getChambresDisponible(dateArrive,dateDepart,nomCategorie,quantite)

note left of mc: Expert\nCategorie contient map<:Categorie>
cat -> mc: :categorie = get(nomCategorie)

note left of ic: Expert\nCategorie possède l'instance locale :categorie\nLes chambres appartiennent a une categorie
cat-> ic: list<:Chambre> chambres = getChambresDisponible(dateArrive,dateDepart,quantite)


note left of r: Exert\nctrl a une visibiilité sur r:Reservation\nr est le créateur de lr
ctrl -> r: creerLigneReservation(dateArrive,dateDepart,chambres)

note left of lr: Createur(PUCE)\nr contient lr
r->lr ** : lr=create(dateArrive,dateDepart,chambres,r:Reservatio)

note left of llr: Expert\nr contient llr\nllr est une liste<:LigneReservation>
r->llr: add(lr)


@enduml
